name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.7"
        - "3.8"
        - "3.9"
    name: Check Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Requirements check
      run: python -m pip list

    - name: Install package
      run: python -m pip install -e . -r requirements.txt

    - name: Test package
      run: python -m pytest tests/

    - name: Install plotting requirements
      run: python -m pip install -e .
